services:
  foodplan-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./foodplan_service:/foodplan_service

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"